[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
NLTK_DATA = "/app/nltk_data"
PYTHONPATH = "/app"

[phases.setup]
nixPkgs = ["python311", "gcc", "pkg-config", "curl"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "mkdir -p /app/nltk_data",
  "python -c \"import nltk; nltk.data.path.append('/app/nltk_data'); nltk.download('punkt', download_dir='/app/nltk_data', quiet=True)\"",
  "python -c \"import nltk; nltk.data.path.append('/app/nltk_data'); nltk.download('brown', download_dir='/app/nltk_data', quiet=True)\"",
  "python -c \"import nltk; nltk.data.path.append('/app/nltk_data'); nltk.download('wordnet', download_dir='/app/nltk_data', quiet=True)\"",
  "python -c \"import textblob; from textblob import download_corpora; download_corpora.download_all()\""
]

[phases.build]
cmds = [
  "mkdir -p uploads models logs",
  "chmod -R 755 uploads models logs"
]

[start]
cmd = "python app.py"